### PR TITLE
load: Enable CORS

### PR DESCRIPTION
**Pull request by adrienverge**
When loading an archive to access a CouchDB instance on `localhost`, it can be useful to access the database from a redirect or reverse proxy like nginx. In such a case, the origin might be `localhost:4200` instead of `localhost:60651`, for example.

To allow this to work in a browser, I propose to enable CORS by default on `couchcopy load …`.

### CODE REVIEW

**Review by H--o-l — APPROVED** [review]
Works for me, I had to add it in code manually a few times myself :ok_hand:

**Comment by adrienverge** [comment]
Thanks!

Sorry about the noise, it also needed this to work properly:
```diff
@@ -267,6 +267,12 @@ async def load(archive, admin=None, tmp_dir=None, blocking=True):
                 f'[httpd]\n'
                 f'port = {port2}\n'
                 f'\n'
+                f'[cors]\n'
+                f'credentials = true\n'
+                f'origins = *\n'
+                f'methods = GET, HEAD, POST, PUT, DELETE\n'
+                f'headers = Accept, Authorization, Content-Type, Origin\n'
+                f'\n'
                 f'[couchdb]\n'
                 f'database_dir = {tmp_dir.name}/data\n'
                 f'view_index_dir = {tmp_dir.name}/data\n'
```

**Comment by H--o-l** [comment]
:+1:

**Comment by adrienverge** [comment]
Thanks

**Pull request merged**
